import type { HostingPlan } from "@/types";

function slugifyPlan(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

const SEED: Omit<HostingPlan, "id">[] = [
  {
    provider: "DigitalOcean",
    providerSlug: "digitalocean",
    name: "Basic 1GB",
    ramGb: 1,
    cpuCores: 1,
    storageGb: 25,
    bandwidthTb: 1,
    priceMonthlyUsd: 6,
    region: "Global",
    affiliateUrl: "https://www.digitalocean.com/pricing/droplets",
    features: ["SSD", "Monitoring", "API"],
  },
  {
    provider: "DigitalOcean",
    providerSlug: "digitalocean",
    name: "Basic 2GB",
    ramGb: 2,
    cpuCores: 1,
    storageGb: 50,
    bandwidthTb: 2,
    priceMonthlyUsd: 12,
    region: "Global",
    affiliateUrl: "https://www.digitalocean.com/pricing/droplets",
    features: ["SSD", "Monitoring", "API"],
  },
  {
    provider: "Vultr",
    providerSlug: "vultr",
    name: "Cloud Compute 1GB",
    ramGb: 1,
    cpuCores: 1,
    storageGb: 25,
    bandwidthTb: 1,
    priceMonthlyUsd: 5,
    region: "Global",
    affiliateUrl: "https://www.vultr.com/pricing/",
    features: ["NVMe", "IPv6", "Snapshots"],
  },
  {
    provider: "Vultr",
    providerSlug: "vultr",
    name: "Cloud Compute 2GB",
    ramGb: 2,
    cpuCores: 1,
    storageGb: 55,
    bandwidthTb: 2,
    priceMonthlyUsd: 10,
    region: "Global",
    affiliateUrl: "https://www.vultr.com/pricing/",
    features: ["NVMe", "IPv6", "Snapshots"],
  },
  {
    provider: "Linode (Akamai)",
    providerSlug: "linode",
    name: "Nanode 1GB",
    ramGb: 1,
    cpuCores: 1,
    storageGb: 25,
    bandwidthTb: 1,
    priceMonthlyUsd: 5,
    region: "Global",
    affiliateUrl: "https://www.linode.com/pricing/",
    features: ["SSD", "Backups optional"],
  },
  {
    provider: "Linode (Akamai)",
    providerSlug: "linode",
    name: "Linode 2GB",
    ramGb: 2,
    cpuCores: 1,
    storageGb: 50,
    bandwidthTb: 2,
    priceMonthlyUsd: 12,
    region: "Global",
    affiliateUrl: "https://www.linode.com/pricing/",
    features: ["SSD", "Backups optional"],
  },
  {
    provider: "Hetzner",
    providerSlug: "hetzner",
    name: "CX22",
    ramGb: 4,
    cpuCores: 2,
    storageGb: 40,
    bandwidthTb: 20,
    priceMonthlyUsd: 4.5,
    region: "EU",
    affiliateUrl: "https://www.hetzner.com/cloud",
    features: ["NVMe", "IPv4+IPv6", "Giá EU"],
  },
  {
    provider: "Hetzner",
    providerSlug: "hetzner",
    name: "CX32",
    ramGb: 8,
    cpuCores: 4,
    storageGb: 80,
    bandwidthTb: 20,
    priceMonthlyUsd: 7.5,
    region: "EU",
    affiliateUrl: "https://www.hetzner.com/cloud",
    features: ["NVMe", "IPv4+IPv6", "Giá EU"],
  },
  {
    provider: "Contabo",
    providerSlug: "contabo",
    name: "Cloud VPS S",
    ramGb: 4,
    cpuCores: 4,
    storageGb: 50,
    bandwidthTb: 32,
    priceMonthlyUsd: 6.99,
    region: "EU/US",
    affiliateUrl: "https://contabo.com/en/vps/",
    features: ["Unlimited traffic*", "Giá rẻ"],
  },
  {
    provider: "Contabo",
    providerSlug: "contabo",
    name: "Cloud VPS M",
    ramGb: 8,
    cpuCores: 6,
    storageGb: 100,
    bandwidthTb: 32,
    priceMonthlyUsd: 10.99,
    region: "EU/US",
    affiliateUrl: "https://contabo.com/en/vps/",
    features: ["Unlimited traffic*", "Giá rẻ"],
  },
];

export const HOSTING_SEED_PLANS: HostingPlan[] = SEED.map((plan) => ({
  ...plan,
  id: `${plan.providerSlug}-${slugifyPlan(plan.name)}`,
}));
